#[derive(Clone, Debug)]
pub enum Token {
    LeftParen,  // '('
    RightParen, // ')'
    LeftBrace,  // '{'
    RightBrace, // '}'
    SemiColon,  // ';'
    Plus,       // '+'
    Minus,      // '-'
    Arrow,      // '->'
    Star,       // '*'
    Slash,      // '/'
    BackSlash,  // '\'
    Percent,    // '%'
    Comma,      // ','
    Dot,        // '.'
    Underscore, // '_'
    Is,         // '='
    Eq,         // '=='
    Gt,         // '>'
    GtEq,       // '>='
    Lt,         // '<'
    LtEq,       // '<='
    Bang,       // '!'
    NotEq,      // '!='
    And,        // '&&'
    Or,         // '||'
    Pipe,       // '|'
    True,       // 'true'
    False,      // 'false'
    Let,        // 'let'
    Function,   // 'fn'
    If,         // 'if'
    For,        // 'for'
    While,      // 'while'
    Return,     // 'return'
    Print,      // 'print'
    Node,       // 'node'
    Number(f64),
    Identifier(String),
    String(String),
}
