/// Scanning/lexing token representation used in the Nexus grammar.
#[derive(Clone, Debug, PartialEq)]
pub enum Token {
    Empty,        // "Empty" token, used for stream preprocessing.
    LeftParen,    // '('
    RightParen,   // ')'
    LeftBrace,    // '{'
    RightBrace,   // '}'
    LeftBracket,  // '['
    RightBracket, // ']'
    Colon,        // ':'
    SemiColon,    // ';'
    Amp,          // '&'
    Plus,         // '+'
    Minus,        // '-'
    Arrow,        // '->'
    Star,         // '*'
    Slash,        // '/'
    BackSlash,    // '\'
    Percent,      // '%'
    Comma,        // ','
    Dot,          // '.'
    Range,        // '..'
    Underscore,   // '_'
    Is,           // '='
    Eq,           // '=='
    Gt,           // '>'
    GtEq,         // '>='
    Lt,           // '<'
    LtEq,         // '<='
    Bang,         // '!'
    NotEq,        // '!='
    And,          // '&&'
    Or,           // '||'
    EmptyClosure, // '||'
    Pipe,         // '|'
    True,         // 'true'
    False,        // 'false'
    Const,        // 'const'
    Let,          // 'let'
    Mut,          // 'mut'
    Function,     // 'fn'
    If,           // 'if'
    Else,         // 'else'
    For,          // 'for'
    In,           // 'in'
    While,        // 'while'
    Return,       // 'return'
    Use,          // 'use'
    BoolId,       // 'bool'
    NodeId,       // 'Node'
    GroupId,      // 'Group'
    NumberId,     // 'Number'
    StringId,     // 'String'
    Print,        // 'print'
    Node,         // 'node'
    Group,        // 'group'
    Number(f64),
    Identifier(String),
    String(String),
}

/// Collection of tokens.
pub type Tokens = Vec<Token>;
